import { EventSettings, StampPoint } from "@/lib/types";

export const STORAGE_KEYS = {
  session: "festival-archive-session",
  stampState: "festival-archive-stamps",
  cards: "festival-archive-cards",
  interests: "festival-archive-interests",
} as const;

export const TODAY_COPY = {
  title: "오늘의 머무름",
  body: "꽃과 문장, 공원과 문화 부스를 천천히 지나며 오늘의 감각을 작은 기록으로 남기는 봄의 아카이브입니다.",
};

export const TOUR_BADGES = [
  "공원 산책자",
  "기록 수집가",
  "문장 탐험가",
  "문화 부스 방문객",
];

export const DEFAULT_STAMP_POINTS: StampPoint[] = [
  {
    id: "point-1",
    slug: "playground",
    title: "놀이터",
    location: "메인 게이트",
    pointType: "location",
    description: "가장 먼저 향기와 인사가 모이는 자리",
    phrase: "오늘의 첫 장면이 여기서 시작됩니다.",
    color: "#E9A17A",
    order: 1,
    icon: "sparkles",
    x: "18%",
    y: "30%",
    isPublished: true,
    qrEnabled: true,
    rewardCopy: "입구의 장면을 기록했습니다.",
  },
  {
    id: "point-2",
    slug: "plaza",
    title: "광장",
    location: "중앙 산책로",
    pointType: "location",
    description: "사람들이 천천히 걸으며 오래 머무는 중심 동선",
    phrase: "당신은 지금 축제의 두 번째 장면을 지나고 있어요.",
    color: "#89A67C",
    order: 2,
    icon: "map-pin",
    x: "50%",
    y: "42%",
    isPublished: true,
    qrEnabled: true,
    rewardCopy: "산책의 리듬이 저장되었습니다.",
  },
  {
    id: "point-3",
    slug: "book-garden",
    title: "책 정원",
    location: "기록소 부스",
    pointType: "booth",
    description: "문장을 만나고 기록이 완성되는 조용한 자리",
    phrase: "이제 오늘의 축제 산책이 하나의 기록으로 남습니다.",
    color: "#D77B57",
    order: 3,
    icon: "tent-tree",
    x: "73%",
    y: "26%",
    isPublished: true,
    qrEnabled: true,
    rewardCopy: "오늘의 배지가 열렸습니다.",
    linkedBoothId: "booth-3",
  },
  {
    id: "point-4",
    slug: "flower-booth-a",
    title: "꽃 부스 A",
    location: "꽃시장 안쪽",
    pointType: "booth",
    description: "오래 머무르게 되는 꽃다발과 라벨의 자리",
    phrase: "꽃잎과 종이 조각이 함께 진열된 장면입니다.",
    color: "#D98B8B",
    order: 4,
    icon: "flower",
    x: "65%",
    y: "57%",
    isPublished: true,
    qrEnabled: true,
    rewardCopy: "꽃 부스의 장면이 저장되었습니다.",
    linkedBoothId: "booth-2",
  },
];

export const DEFAULT_EVENT_SETTINGS: EventSettings = {
  eventName: "#8 율량마르쉐 애착꽃시장",
  heroTitle: "살아있던 적이 없는 꽃을 팝니다,\n그런데 이제 영원히 시들지 않는.",
  heroDescription:
    "봄의 공원에 잠시 펼쳐진 꽃시장과 문화 마켓, 한 조각의 문장과 기록이 오래 남는 느린 산책형 아카이브입니다.",
  eventDate: "2026.03.12",
  eventPlace: "청주 율량동 공원 & 애착꽃시장",
  operationHours: "13:00 - 18:00",
  notice: "현장에 남겨진 문장과 순간은 행사 분위기를 지키기 위해 운영자가 검수할 수 있습니다.",
  archiveNotice:
    "오늘의 애착꽃시장은 문을 닫았어요. 이제 이 사이트는 남겨진 문장과 순간을 천천히 읽는 아카이브 모드로 전환되었습니다.",
  introSteps: [
    "게스트로 바로 입장하고 오늘의 이름을 가볍게 남깁니다.",
    "현장 QR을 스캔해 꽃시장과 공원의 장면 스탬프를 모읍니다.",
    "공원에 한 줄 또는 오늘의 순간을 남겨 문장 아카이브에 참여합니다.",
    "투어를 마치면 당신의 하루가 카드 한 벌의 기록으로 정리됩니다.",
  ],
  momentTags: ["꽃", "산책", "버스킹", "책", "머무름", "기록"],
  ctaLabels: {
    start: "오늘의 산책 시작하기",
    guestbook: "공원에 한 줄 남기기",
    moments: "오늘의 순간 남기기",
    card: "기록 카드 만들기",
  },
  sectionVisibility: {
    showMap: true,
    showPrograms: true,
    showBooths: true,
    showQuoteDraw: true,
    showGuestbookShortcut: true,
    showCardBanner: true,
  },
  siteMode: "live",
  stampCompletionRule: {
    requiredCount: 4,
    locationRequired: 2,
    boothRequired: 2,
  },
  programs: [
    { id: "program-1", time: "13:00", title: "버스킹이 열리는 시간", detail: "꽃시장과 공원 사이의 작은 무대가 열립니다.", location: "잔디광장", status: "live", isPublished: true, order: 1 },
    { id: "program-2", time: "14:00", title: "머무는 동선 안내", detail: "입구에서 산책길, 기록소까지 천천히 걷는 추천 루트", location: "안내 데스크", status: "upcoming", isPublished: true, order: 2 },
    { id: "program-3", time: "15:00", title: "문화 부스 큐레이션", detail: "작가와 독립출판, 꽃과 문장을 소개하는 시간", location: "문화 부스", status: "upcoming", isPublished: true, order: 3 },
    { id: "program-4", time: "16:00", title: "기록 카드 소개", detail: "오늘 남겨진 문장과 순간이 카드 한 벌로 정리됩니다.", location: "기록 부스", status: "upcoming", isPublished: true, order: 4 },
  ],
  booths: [
    {
      id: "booth-1",
      name: "문장 책방",
      authorName: "서유림",
      subtitle: "책과 엽서를 천천히 고르는 조용한 자리",
      description: "공원에서 읽기 좋은 독립출판과 봄의 엽서 문장을 한 권씩 펼쳐보는 부스입니다.",
      bookTitle: "천천히 머무는 문장들",
      imageUrl: "/books/book-1.svg",
      bookDescription: "공원에서 천천히 읽기 좋은 짧은 산문과 문장들을 엮은 작은 책입니다.",
      quote: "오늘은 조금 천천히 걸어도 괜찮다.",
      favoriteQuote: "천천히 읽은 문장만이 오래 남는 저녁이 있다.",
      authorMessage: "꽃시장 한가운데서 문장을 펼쳐보는 순간이 누군가의 봄으로 남기를 바랍니다.",
      bookPrice: "12,000원",
      bookStock: 14,
      participationType: "현장 판매 + 큐레이션",
      isOnsite: true,
      isConsignment: false,
      snsLink: "https://instagram.com/yullang_sentence_books",
      mapLabel: "기록소 옆 문장 책방",
      order: 1,
    },
    {
      id: "booth-2",
      name: "꽃시장 아카이브",
      authorName: "정하늬",
      subtitle: "꽃과 포스터, 색의 조각을 모아두는 자리",
      description: "꽃다발과 시장 풍경을 작은 카드, 포스터, 색의 표본처럼 차분하게 기록합니다.",
      bookTitle: "색의 기록",
      imageUrl: "/books/book-2.svg",
      bookDescription: "꽃시장 풍경과 색의 표본을 포스터와 산문으로 엮은 큐레이션 북입니다.",
      quote: "꽃과 문장 사이에서 하루가 정리된다.",
      favoriteQuote: "다정한 색 하나가 하루의 결을 바꾸기도 한다.",
      authorMessage: "오래 보관하고 싶은 꽃의 온도와 시장의 색을 책의 장면처럼 엮었습니다.",
      bookPrice: "15,000원",
      bookStock: 8,
      participationType: "전시 + 판매",
      isOnsite: true,
      isConsignment: true,
      snsLink: "https://instagram.com/flower_archive_market",
      mapLabel: "꽃시장 안쪽 아카이브 테이블",
      order: 2,
    },
    {
      id: "booth-3",
      name: "공원 기록소",
      authorName: "김연서",
      subtitle: "방문객의 한 줄과 장면을 모으는 기록 부스",
      description: "오늘 남겨진 문장과 사진, 스탬프가 카드뉴스와 함께 한 권의 봄 아카이브처럼 쌓입니다.",
      bookTitle: "머무름의 아카이브",
      imageUrl: "/books/book-3.svg",
      bookDescription: "방문객의 문장과 공원의 장면을 기록물처럼 엮어낸 행사 아카이브 북입니다.",
      quote: "머무른 시간은 기록이 될 때 더 오래 남는다.",
      favoriteQuote: "잠시 앉아 적은 메모 하나가 오래 남는 지도가 되기도 한다.",
      authorMessage: "행사가 끝난 뒤에도 방문객의 한 줄이 사라지지 않도록 기록의 서랍을 만들었습니다.",
      bookPrice: "18,000원",
      bookStock: 5,
      participationType: "참여형 기록 부스",
      isOnsite: true,
      isConsignment: false,
      snsLink: "https://instagram.com/park_archive_lab",
      mapLabel: "중앙 기록 부스",
      order: 3,
    },
  ],
  quotes: [
    { id: "quote-1", text: "잠깐 머문 장소가 오래 남는 날이 있다.", author: "서유림", sourceBook: "천천히 머무는 문장들", category: "머무름", isPublished: true, isFeatured: true },
    { id: "quote-2", text: "오늘은 조금 천천히 걸어도 괜찮다.", author: "서유림", sourceBook: "천천히 머무는 문장들", category: "산책", isPublished: true, isFeatured: false },
    { id: "quote-3", text: "꽃과 문장 사이에서 하루가 정리된다.", author: "정하늬", sourceBook: "색의 기록", category: "기록", isPublished: true, isFeatured: false },
    { id: "quote-4", text: "머무른 시간은 기록이 될 때 더 오래 남는다.", author: "김연서", sourceBook: "머무름의 아카이브", category: "아카이브", isPublished: true, isFeatured: false },
  ],
  cardTemplate: {
    card1Title: "#8 율량마르쉐 애착꽃시장",
    card2Title: "오늘의 문장",
    finalMessage: "살아있던 적이 없는 꽃을 만나고, 시들지 않는 기록을 남긴 방문자에게 건네는 오늘의 배지입니다.",
    badgePrefix: "오늘의 애착 배지",
    saveButtonLabel: "카드 이미지 저장하기",
    themeName: "spring-collage",
  },
};

export const BAD_WORDS = ["욕설", "비속어", "바보"];
export const GUESTBOOK_LIMIT = 80;
export const MOMENT_LIMIT = 140;
export const RATE_LIMIT_MS = 30_000;
export const GENERATED_CARD_LIMIT = 12;
export const ADMIN_COOKIE_NAME = "festival-admin-session";
export const ADMIN_SESSION_HOURS = 8;

export const ROLE_LABELS = {
  super_admin: "슈퍼관리자",
  content_manager: "실무 운영자",
  field_moderator: "현장모더레이터",
} as const;

export const ROLE_TABS = {
  super_admin: [
    "overview",
    "settings",
    "landing",
    "programs",
    "stamps",
    "qr",
    "booths",
    "quotes",
    "cards",
    "content",
    "status",
    "access",
    "logs",
  ],
  content_manager: [
    "overview",
    "settings",
    "landing",
    "programs",
    "stamps",
    "qr",
    "booths",
    "quotes",
    "cards",
    "content",
    "status",
  ],
  field_moderator: ["overview", "programs", "content"],
} as const;
