import { EventSettings, StampPoint } from "@/lib/types";

export const STORAGE_KEYS = {
  session: "festival-archive-session",
  stampState: "festival-archive-stamps",
  cards: "festival-archive-cards",
  interests: "festival-archive-interests",
} as const;

export const TODAY_COPY = {
  title: "오늘의 머무름",
  body: "꽃과 문장, 공원과 문화 부스를 천천히 지나며 오늘의 감각을 작은 기록으로 남기는 봄의 아카이브입니다.",
};

export const TOUR_BADGES = [
  "공원 산책자",
  "기록 수집가",
  "문장 탐험가",
  "문화 부스 방문객",
];

export const DEFAULT_STAMP_POINTS: StampPoint[] = [
  {
    id: "point-1",
    slug: "playground",
    title: "놀이터",
    location: "메인 게이트",
    pointType: "location",
    description: "가장 먼저 향기와 인사가 모이는 자리",
    phrase: "오늘의 첫 장면이 여기서 시작됩니다.",
    color: "#E9A17A",
    order: 1,
    icon: "sparkles",
    x: "18%",
    y: "30%",
    isPublished: true,
    qrEnabled: true,
    rewardCopy: "입구의 장면을 기록했습니다.",
  },
  {
    id: "point-2",
    slug: "plaza",
    title: "광장",
    location: "중앙 산책로",
    pointType: "location",
    description: "사람들이 천천히 걸으며 오래 머무는 중심 동선",
    phrase: "당신은 지금 축제의 두 번째 장면을 지나고 있어요.",
    color: "#89A67C",
    order: 2,
    icon: "map-pin",
    x: "50%",
    y: "42%",
    isPublished: true,
    qrEnabled: true,
    rewardCopy: "산책의 리듬이 저장되었습니다.",
  },
  {
    id: "point-3",
    slug: "book-garden",
    title: "책 정원",
    location: "기록소 부스",
    pointType: "booth",
    description: "문장을 만나고 기록이 완성되는 조용한 자리",
    phrase: "이제 오늘의 축제 산책이 하나의 기록으로 남습니다.",
    color: "#D77B57",
    order: 3,
    icon: "tent-tree",
    x: "73%",
    y: "26%",
    isPublished: true,
    qrEnabled: true,
    rewardCopy: "오늘의 배지가 열렸습니다.",
    linkedBoothId: "booth-3",
  },
  {
    id: "point-4",
    slug: "essay-booth",
    title: "산문 부스",
    location: "작가 라인 B",
    pointType: "booth",
    description: "황주영 작가의 산문집을 만나는 자리",
    phrase: "보이지 않게 탁해지는 마음을 문장으로 환기하는 공간입니다.",
    color: "#D98B8B",
    order: 4,
    icon: "flower",
    x: "65%",
    y: "57%",
    isPublished: true,
    qrEnabled: true,
    rewardCopy: "산문 부스의 장면이 저장되었습니다.",
    linkedBoothId: "booth-4",
  },
];

export const DEFAULT_EVENT_SETTINGS: EventSettings = {
  eventName: "율량마르쉐#8 작가 · 책 부스",
  heroTitle: "율량마르쉐#8\n작가와 책을 만나는\n독서 부스 아카이브",
  heroDescription:
    "청주 율량마르쉐#8의 참여 작가와 도서를 한눈에 살펴보고, 키워드 기반 추천으로 취향에 맞는 책을 발견하는 독서 부스 페이지입니다.",
  featuredBookBoothId: "booth-1",
  eventDate: "2026.03.28 - 29",
  eventPlace: "청주 율량동 공원 · 율량마르쉐#8",
  operationHours: "11:00 - 17:30",
  notice: "작가 및 책 소개 내용은 운영 기준에 따라 최신 정보로 갱신될 수 있습니다.",
  archiveNotice:
    "행사가 종료되어도 이 페이지에서 참여 작가와 도서 정보를 다시 확인할 수 있습니다.",
  introSteps: [
    "참여 작가 도서와 일반 서적 추천 부스를 카드 형태로 빠르게 둘러봅니다.",
    "작가명/책 제목 키워드로 원하는 도서를 검색합니다.",
    "추천 우선순위 슬라이더로 맞춤 추천 비율을 조정합니다.",
    "관심 작가와 도서를 저장해 다시 찾아봅니다.",
  ],
  momentTags: ["독서", "책", "작가", "시집", "산문", "추천"],
  ctaLabels: {
    start: "작가 · 책 부스 보기",
    guestbook: "독자 메시지 남기기",
    moments: "책 추천 후기 남기기",
    card: "책 카드 만들기",
  },
  sectionVisibility: {
    showMap: true,
    showPrograms: true,
    showBooths: true,
    showQuoteDraw: true,
    showGuestbookShortcut: true,
    showCardBanner: true,
  },
  siteMode: "live",
  stampCompletionRule: {
    requiredCount: 4,
    locationRequired: 2,
    boothRequired: 2,
  },
  programs: [
    { id: "program-1", time: "13:00", title: "버스킹이 열리는 시간", detail: "꽃시장과 공원 사이의 작은 무대가 열립니다.", location: "잔디광장", status: "live", isPublished: true, order: 1 },
    { id: "program-2", time: "14:00", title: "머무는 동선 안내", detail: "입구에서 산책길, 기록소까지 천천히 걷는 추천 루트", location: "안내 데스크", status: "upcoming", isPublished: true, order: 2 },
    { id: "program-3", time: "15:00", title: "문화 부스 큐레이션", detail: "작가와 독립출판, 꽃과 문장을 소개하는 시간", location: "문화 부스", status: "upcoming", isPublished: true, order: 3 },
    { id: "program-4", time: "16:00", title: "기록 카드 소개", detail: "오늘 남겨진 문장과 순간이 카드 한 벌로 정리됩니다.", location: "기록 부스", status: "upcoming", isPublished: true, order: 4 },
  ],
  booths: [
    {
      id: "booth-1",
      name: "이윤지",
      authorName: "이윤지",
      subtitle: "에세이",
      description: "몸을 치료하는 간호사이자 마음을 치유하는 작가입니다.",
      bookTitle: "간호사로 사라지다 단원병 환아 엄마로 살아지다",
      imageUrl: "/books/간호사로 사라지다 단원병 환아 엄마로 살아지다.jpg",
      bookDescription:
        "배우이자 작가 차인표님의 추천 도서. 간호사이자 엄마, 의료인이자 가족 간병인이라는 두 정체성을 살아온 저자의 담담한 고백으로, 어떤 고통 속에서도 삶을 이어가고자 하는 모든 이들에게 위로와 희망을 건넵니다.",
      quote: "어느 순간부터 주어진 삶을 다독이며 다정하게 바라보기 시작했더니, 세상도 조금씩 다정한 응답을 주기 시작합니다.",
      favoriteQuote: "어느 순간부터 주어진 삶을 다독이며 다정하게 바라보기 시작했더니, 세상도 조금씩 다정한 응답을 주기 시작합니다.",
      authorMessage:
        "지친 하루의 끝에서, 따뜻한 위로를 받을 수 있는 힐링 에세이를 쓰고 있습니다.",
      bookPrice: "12,000원",
      bookStock: 2,
      participationType: "작가 부스",
      isOnsite: true,
      isConsignment: true,
      mapLabel: "이윤지 작가 부스",
      snsLink: "https://instagram.com/iam.yunji",
      order: 1,
    },
    {
      id: "booth-2",
      name: "이윤지",
      authorName: "이윤지",
      subtitle: "에세이",
      description:
        "몸을 치료하는 간호사이자 마음을 치유하는 작가입니다.",
      bookTitle: "고질라와 헤엄치다",
      imageUrl: "/books/고질라와 헤엄치다.jpg",
      bookDescription:
        "고질은 오래 앓고 있는, 고치기 어려운 병을 뜻합니다. 고질라와 헤엄친다는 말처럼 삶은 계속되고, 그 안에도 희망이 남아 있다는 메시지를 담은 책입니다.",
      quote: "이곳은 광활한 우주이고, 우리는 반짝이는 네 개의 별.",
      favoriteQuote: "이곳은 광활한 우주이고, 우리는 반짝이는 네 개의 별.",
      authorMessage:
        "지친 하루의 끝에서, 따뜻한 위로를 받을 수 있는 힐링 에세이를 쓰고 있습니다.",
      bookPrice: "10,000원",
      bookStock: 2,
      participationType: "작가 부스",
      isOnsite: true,
      isConsignment: true,
      mapLabel: "이윤지 작가 부스",
      snsLink: "https://instagram.com/iam.yunji",
      order: 2,
    },
    {
      id: "booth-3",
      name: "이윤지",
      authorName: "이윤지",
      subtitle: "에세이",
      description: "몸을 치료하는 간호사이자 마음을 치유하는 작가입니다.",
      bookTitle: "층간소음 블렌딩",
      imageUrl: "/books/층간소음 블렌딩.jpg",
      bookDescription:
        "긴 글이 부담스러운 분, 독서에 입문하고 싶은 분께 추천하는 책입니다. 숏츠 대신 하루 한 페이지만 읽어도 되는 구성으로, 평범한 일상에서 깊은 울림을 발견할 수 있습니다.",
      quote: "작은 행운을 찾아 큰 행복을 만드는 사람.",
      favoriteQuote: "작은 행운을 찾아 큰 행복을 만드는 사람.",
      authorMessage:
        "지친 하루의 끝에서, 따뜻한 위로를 받을 수 있는 힐링 에세이를 쓰고 있습니다.",
      bookPrice: "10,000원",
      bookStock: 4,
      participationType: "작가 부스",
      isOnsite: true,
      isConsignment: true,
      mapLabel: "이윤지 작가 부스",
      snsLink: "https://instagram.com/iam.yunji",
      order: 3,
    },
    {
      id: "booth-4",
      name: "이윤지",
      authorName: "이윤지",
      subtitle: "에세이",
      description: "몸을 치료하는 간호사이자 마음을 치유하는 작가입니다.",
      bookTitle: "그래도 오늘은 다르게 살기로 했다",
      imageUrl: "/books/그래도 오늘은 다르게 살기로 했다.jpg",
      bookDescription:
        "야무진 루틴 하나가 삶을 바꾸기 시작했다는 메시지를 담은 책입니다. 반복되는 하루를 바꾼 10인의 사적인 기록을 통해 평범한 사람들의 현실적인 변화를 보여줍니다.",
      quote: "사소한 일상에서 즐거움을 찾고, 그걸 붙들며 하루를 살아가는 삶. 이런 하루하루가 쌓여 결국 괜찮은 삶이 된다.",
      favoriteQuote: "사소한 일상에서 즐거움을 찾고, 그걸 붙들며 하루를 살아가는 삶. 이런 하루하루가 쌓여 결국 괜찮은 삶이 된다.",
      authorMessage:
        "지친 하루의 끝에서, 따뜻한 위로를 받을 수 있는 힐링 에세이를 쓰고 있습니다.",
      bookPrice: "10,000원",
      bookStock: 4,
      participationType: "작가 부스",
      isOnsite: true,
      isConsignment: true,
      mapLabel: "이윤지 작가 부스",
      snsLink: "https://instagram.com/iam.yunji",
      order: 4,
    },
    {
      id: "booth-5",
      name: "이윤지",
      authorName: "이윤지",
      subtitle: "에세이",
      description: "몸을 치료하는 간호사이자 마음을 치유하는 작가입니다.",
      bookTitle: "그래서 오늘도 사랑합니다",
      imageUrl: "/books/그래서 오늘도 사랑합니다.jpg",
      bookDescription:
        "부모, 자녀, 부부, 반려동물, 오래된 물건, 스쳐 지나간 인연과 여전히 곁에 있는 사람들까지 각기 다른 온도의 사랑 이야기를 담았습니다. 사랑이 오늘을 살아가게 하는 조용한 힘임을 전합니다.",
      quote: "서로를 배려하기도, 섭섭해하기도, 안쓰러워하기도 하는 마음을 사랑이라고 퉁 치며 그럭저럭 살아가고 있다.",
      favoriteQuote: "서로를 배려하기도, 섭섭해하기도, 안쓰러워하기도 하는 마음을 사랑이라고 퉁 치며 그럭저럭 살아가고 있다.",
      authorMessage:
        "지친 하루의 끝에서, 따뜻한 위로를 받을 수 있는 힐링 에세이를 쓰고 있습니다.",
      bookPrice: "10,000원",
      bookStock: 16,
      participationType: "작가 부스",
      isOnsite: true,
      isConsignment: true,
      mapLabel: "이윤지 작가 부스",
      snsLink: "https://instagram.com/iam.yunji",
      order: 5,
    },
    {
      id: "booth-6",
      name: "이윤지",
      authorName: "이윤지",
      subtitle: "에세이",
      description: "몸을 치료하는 간호사이자 마음을 치유하는 작가입니다.",
      bookTitle: "오늘도 덕분에 숨을 쉽니다",
      imageUrl: "/books/오늘도 덕분에 숨을 쉽니다.jpg",
      bookDescription:
        "당신을 숨 쉬게 하는 것은 무엇인가요라는 질문에서 시작된 11인 11색 덕질 이야기로, 진심으로 기쁨과 춤추는 시간으로 독자를 초대합니다.",
      quote: "책 속의 문장들은 우리 가정에 닥친 시련을 절망에서 희망으로 이끌어 주었다.",
      favoriteQuote: "책 속의 문장들은 우리 가정에 닥친 시련을 절망에서 희망으로 이끌어 주었다.",
      authorMessage:
        "지친 하루의 끝에서, 따뜻한 위로를 받을 수 있는 힐링 에세이를 쓰고 있습니다.",
      bookPrice: "10,000원",
      bookStock: 3,
      participationType: "작가 부스",
      isOnsite: true,
      isConsignment: true,
      mapLabel: "이윤지 작가 부스",
      snsLink: "https://instagram.com/iam.yunji",
      order: 6,
    },
    {
      id: "booth-7",
      name: "황주영",
      authorName: "황주영",
      subtitle: "산문집",
      description: "보이지 않지만 분명히 탁해져 가는 것들에 대한 이야기입니다.",
      bookTitle: "필터 교체가 필요합니다",
      imageUrl: "/books/필터교체가필요합니다.jpg",
      bookDescription:
        "우리는 매일 같은 하루를 살지만, 그 하루는 조금씩 무너지고 있습니다. 출근길의 사람들, 서울이라는 구조, 집이라는 빚, 직장 내 침묵과 부조리, 그리고 점점 무뎌지는 감정들. 이 모든 것들이 하나의 문장으로 반복됩니다. 필터 교체가 필요합니다.",
      quote: "교체해야 하는 건 무엇인가",
      favoriteQuote: "교체해야 하는 건 무엇인가",
      authorMessage:
        "우리는 왜 멈추지 못하는가\n왜 부조리를 알면서도 침묵하는가\n왜 삶은 점점 무뎌지는가",
      bookPrice: "12,800원",
      bookStock: 6,
      participationType: "작가 부스",
      isOnsite: true,
      isConsignment: true,
      mapLabel: "황주영 작가 부스",
      order: 7,
    },
    {
      id: "booth-8",
      name: "황주영",
      authorName: "황주영",
      subtitle: "시집",
      description:
        "저는 제가 쓰는 글들을 끄적끄적이라고 합니다. 끄적이는 글들이 모여 하나의 문장이 되고, 그 문장이 독자들에게 소중한 순간이 되었으면 좋겠습니다.",
      bookTitle: "어제와 다른 내가 되어",
      imageUrl: "/books/어제와 다른 내가 되어.jpg",
      bookDescription:
        "어제와 다른 내가 되어는 시집의 형태를 한 문장집에 가깝습니다. 어떤 문장은 힘을, 어떤 문장은 자기 성찰을 하게 되는 내용을 담고 있습니다.",
      quote: "내가 살아오며 느낀 것들.",
      favoriteQuote: "내가 살아오며 느낀 것들.",
      authorMessage:
        "나가 바라보는 세상과 너가 바라보는 세상이 다르듯, 더 넓은 세상을 바라보게 되는 순간들이 되었으면 좋겠습니다.",
      bookPrice: "12,000원",
      bookStock: 8,
      participationType: "작가 부스",
      isOnsite: true,
      isConsignment: true,
      mapLabel: "황주영 작가 부스",
      order: 8,
    },
    {
      id: "booth-9",
      name: "신현준",
      authorName: "신현준",
      subtitle: "시집",
      description: "상실 이후에도 마르지 않는 마음의 시간을 시로 기록합니다.",
      bookTitle: "나,비",
      imageUrl: "/books/나,비.jpg",
      bookDescription:
        "나, 비는 상실 이후에도 쉽게 마르지 않는 마음을 기록한 시집입니다. 날아간 사람과 그 자리에 남은 사람 사이, 그 틈에서 오래 머문 감정의 시간을 담았습니다.",
      quote: "상실에 의한 그리움을 담았습니다.",
      favoriteQuote: "상실에 의한 그리움을 담았습니다.",
      authorMessage:
        "나는 비가 되어 기다렸고\n그는 나비였을지 모릅니다.\n이 시집은 사라진 것들을 붙잡기 위한 언어가 아니라\n사라진 뒤에도 남아 있는 마음에 대한 기록입니다.",
      bookPrice: "9,900원",
      bookStock: 10,
      participationType: "작가 부스",
      isOnsite: true,
      isConsignment: true,
      mapLabel: "신현준 작가 부스",
      snsLink: "https://instagram.com/nabistory0918",
      order: 9,
    },
    {
      id: "booth-10",
      name: "신유진",
      authorName: "신유진",
      subtitle: "시집",
      description: "열아홉의 치열한 감정과 성장의 흔적을 시선으로 남깁니다.",
      bookTitle: "별을끄다",
      imageUrl: "/books/별을끄다.jpg",
      bookDescription:
        "별을 끄다 는 열아홉의 시선으로 기록한 감정의 성장기입니다. 사랑의 시작과 기다림, 붕괴와 체념을 지나 다시 세계를 바라보는 시간을 담았습니다.",
      quote: "열 아홉의 치열했던 기록",
      favoriteQuote: "열 아홉의 치열했던 기록",
      authorMessage:
        "열 아홉의 감정을 붙잡은 흔적입니다.\n별을 끄는 것은 사랑을 지우는 게 아니라\n그 빛을 견디지 못한 마음의 고백이었습니다.",
      bookPrice: "8,600원",
      bookStock: 10,
      participationType: "작가 부스",
      isOnsite: true,
      isConsignment: true,
      mapLabel: "신유진 작가 부스",
      snsLink: "https://instagram.com/nabistory0918",
      order: 10,
    },
  ],
  quotes: [
    { id: "quote-1", text: "어느 순간부터 주어진 삶을 다독이며 다정하게 바라보기 시작했더니, 세상도 조금씩 다정한 응답을 주기 시작합니다.", author: "이윤지", sourceBook: "간호사로 사라지다 단원병 환아 엄마로 살아지다", category: "회복", isPublished: true, isFeatured: true },
    { id: "quote-2", text: "이곳은 광활한 우주이고, 우리는 반짝이는 네 개의 별.", author: "이윤지", sourceBook: "고질라와 헤엄치다", category: "희망", isPublished: true, isFeatured: false },
    { id: "quote-3", text: "작은 행운을 찾아 큰 행복을 만드는 사람.", author: "이윤지", sourceBook: "층간소음 블렌딩", category: "일상", isPublished: true, isFeatured: false },
    { id: "quote-4", text: "사소한 일상에서 즐거움을 찾고, 그걸 붙들며 하루를 살아가는 삶. 이런 하루하루가 쌓여 결국 괜찮은 삶이 된다.", author: "이윤지", sourceBook: "그래도 오늘은 다르게 살기로 했다", category: "루틴", isPublished: true, isFeatured: false },
    { id: "quote-5", text: "서로를 배려하기도, 섭섭해하기도, 안쓰러워하기도 하는 마음을 사랑이라고 퉁 치며 그럭저럭 살아가고 있다.", author: "이윤지", sourceBook: "그래서 오늘도 사랑합니다", category: "사랑", isPublished: true, isFeatured: false },
    { id: "quote-6", text: "책 속의 문장들은 우리 가정에 닥친 시련을 절망에서 희망으로 이끌어 주었다.", author: "이윤지", sourceBook: "오늘도 덕분에 숨을 쉽니다", category: "덕질", isPublished: true, isFeatured: false },
    { id: "quote-7", text: "교체해야 하는 건 무엇인가", author: "황주영", sourceBook: "필터 교체가 필요합니다", category: "질문", isPublished: true, isFeatured: false },
    { id: "quote-8", text: "내가 살아오며 느낀 것들.", author: "황주영", sourceBook: "어제와 다른 내가 되어", category: "성찰", isPublished: true, isFeatured: false },
    { id: "quote-9", text: "상실에 의한 그리움을 담았습니다.", author: "신현준", sourceBook: "나,비", category: "그리움", isPublished: true, isFeatured: false },
    { id: "quote-10", text: "열 아홉의 치열했던 기록", author: "신유진", sourceBook: "별을끄다", category: "성장", isPublished: true, isFeatured: false },
  ],
  cardTemplate: {
    card1Title: "율량마르쉐#8 작가 · 책 부스",
    card2Title: "오늘의 문장",
    finalMessage: "좋아하는 문장과 작가를 발견한 방문자에게 건네는 오늘의 독서 기록입니다.",
    badgePrefix: "오늘의 독서 배지",
    saveButtonLabel: "카드 이미지 저장하기",
    themeName: "spring-collage",
  },
};

export const BAD_WORDS = ["욕설", "비속어", "바보"];
export const GUESTBOOK_LIMIT = 80;
export const MOMENT_LIMIT = 140;
export const RATE_LIMIT_MS = 30_000;
export const GENERATED_CARD_LIMIT = 12;
export const ADMIN_COOKIE_NAME = "festival-admin-session";
export const ADMIN_SESSION_HOURS = 8;

export const ROLE_LABELS = {
  super_admin: "슈퍼관리자",
  content_manager: "실무 운영자",
  field_moderator: "현장모더레이터",
} as const;

export const ROLE_TABS = {
  super_admin: [
    "overview",
    "settings",
    "landing",
    "programs",
    "stamps",
    "qr",
    "booths",
    "quotes",
    "cards",
    "content",
    "status",
    "access",
    "logs",
  ],
  content_manager: [
    "overview",
    "settings",
    "landing",
    "programs",
    "stamps",
    "qr",
    "booths",
    "quotes",
    "cards",
    "content",
    "status",
  ],
  field_moderator: ["overview", "programs", "content"],
} as const;
