create table if not exists booth_profiles (
  id text primary key,
  booth_type text not null,
  display_name text not null,
  author_name text,
  activity_name text,
  bio text,
  book_title text,
  book_cover_url text,
  book_description text,
  book_price text,
  book_stock integer default 0,
  highlight_quote text,
  favorite_quote text,
  author_message text,
  participation_type text,
  is_onsite boolean not null default false,
  is_consignment boolean not null default false,
  external_link text,
  sns_link text,
  is_published boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  updated_by text
);
