create table if not exists stamp_points (
  id text primary key,
  name text not null,
  slug text not null unique,
  point_type text not null default 'location',
  location text,
  icon_name text,
  short_copy text,
  description text,
  map_x text,
  map_y text,
  order_index integer not null default 0,
  recommended_order integer not null default 0,
  is_stamp_enabled boolean not null default true,
  is_published boolean not null default true,
  qr_enabled boolean not null default true,
  reward_copy text,
  linked_booth_id text,
  qr_active boolean not null default true,
  color text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  updated_by text
);
